version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/EscuelaItaliana
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - red-dynacord

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
      - ./mongo-init/backup/EscuelaItaliana:/backup/EscuelaItaliana:ro
    networks:
      - red-dynacord

networks:
  red-dynacord:

volumes:
  mongo-data:
