version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://eliana4118:bH13iMJny4PvzTTq@backmongo.7ivep.mongodb.net/EscuelaItaliana?retryWrites=true&w=majority
      - PORT=3000
    networks:
      - red-dynacord
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red-dynacord
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - red-dynacord
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
  
networks:
  red-dynacord: